### ISSUE TITLE
The app only generates the audio of a little part of the epub.

### ISSUE THREAD

**Issue by nandosssssss** [DrewThomasson/ebook2audiobook#1067]
This is just a rudimentary guide, don't be too intimidated, You don't have to follow this to the tee
BEFORE TO OPEN AN ISSUE, MAKE SURE THAT IT HASN'T ALREADY BEEN SOLVED OR REPORTED. :)
Check it with the issue search field

Script Mode

Gradio/GUI

Script Version

25.8.18

Process Mode

Operating System:

Windows 11

Command Line used to start 

ebook2audiobook.cmd

Details
Describe the bug

The app only generates the audio of a little part of the epub.

It sounds well and uses well the reference audio, but only with a small part of the epub.

I have tried with several books, in different formats: epub mobi txt, etc

I have closed the terminal and the browser many times. And I have restarted the computer.

You can find the terminal log here:
https://privatebin.net/?6c01e68912873edb#6MB4gtYhoK9Kdr63Vo7QzdtKQULiPU5VZXM3vq9AQunm

Thanks

**Comment by nandosssssss** [comment]
Thanks for the help. I’ll close the post

**Comment by ROBERT-MCDOWELL** [comment]
your issue is indeed a duplicate of #1066 which I fixed for the next release.

**Comment by nandosssssss** [comment]
I think it’s no the same error. That post talks about “ I noticed a problem when the text contains times in such a format as, for example, 00:00 , 12:30 ,. . .” but I have problems with every epub I tried. It begins to generate the audio using a reference but it always stops after several phrases. The audio generated is almost perfect but it only generates some phrases

**Comment by nandosssssss** [comment]
I think it’s no the same error. That post talks about “ I noticed a problem when the text contains times in such a format as, for example, 00:00 , 12:30 ,. . .” but I have problems with every epub I tried. It begins to generate the audio using a reference audio but it always stops after several phrases. The audio generated is almost perfect but it only generates some phrases 

May be I am doing something wrong. I ave tried with different EPUBs even converting them into other formats like txt and so. 

I don’t want to bother you. Your app is great anyway. I just wanted to hear my epubs with the voice I like most. Many thanks

**Comment by ROBERT-MCDOWELL** [comment]
yes it's the same, the logs show it clearly. having this issue on time formatted lik xx:xx so some sentences following it can miss...

**Comment by nandosssssss** [comment]
Ok. Many thanks

**Comment by ROBERT-MCDOWELL** [comment]
btw if you can share the ebook you want to convert it will help.

**Comment by nandosssssss** [comment]
Here you have two examples:
https://www.transfernow.net/dl/20250929n0p0Sdyo
I have tried many epubs and I have change the format of some of them
But the same error happens
I hope it helps
Many thanks for your support

**Comment by ROBERT-MCDOWELL** [comment]
what TTS engine did you use? xtts, bark etc?, internal fine tuned model?

**Comment by nandosssssss** [comment]
I used XTTS, It's my favourite

**Comment by staringatphones** [comment]
I am also having this issue, so I’m excited to hear it’s fixed in the next update. Is there a timeline for when this will be available?

**Comment by ROBERT-MCDOWELL** [comment]
> I am also having this issue, so I’m excited to hear it’s fixed in the next update. Is there a timeline for when this will be available?

provide your file causing the issue.

**Comment by guillevc** [comment]
I am also having this issue with a lot of books, both in english and spanish.

For example this epub in Spanish, using xtts on an m1 macbook pro: https://www.transfernow.net/dl/20251001Ppr2utvr
Cuts off after 1 minute.

logs: https://pastebin.com/j0rZWgAT

**Comment by ROBERT-MCDOWELL** [comment]
> I am also having this issue with a lot of books, both in english and spanish.
> 
> For example this epub in Spanish, using xtts on an m1 macbook pro: https://www.transfernow.net/dl/20251001Ppr2utvr Cuts off after 1 minute.
> 
> logs: https://pastebin.com/j0rZWgAT

your issue is else and fixed for the coming update.

**Comment by Alan-Cheng** [comment]
Hi, I’m still experiencing this issue when converting Chinese books (中文電子書) using xtts.

I pulled the latest image from Docker Hub (docker pull athomasson2/ebook2audiobook) before running it, so it should be up to date.

Just wondering — has the fix you mentioned (“fixed for the coming update”) already been released?

Thanks again for your work on this project!

**Comment by ROBERT-MCDOWELL** [comment]
as we are not paid and receive not enough donations at all (unfortunately despite of 12.8k stars we got USD100 in almost one year)
and as time is money my answer is simple. it will come when it will come..... too many people think open source means work for free.... which show how many have a very low consciousness and empathy.

**Comment by DrewThomasson** [comment]
The current Dockerfile is actually behind the latest version release as the latest is failing on build (as you can see on the readme Badge) , I'll see if I can find time to fix it.

https://github.com/DrewThomasson/ebook2audiobook/actions/runs/18666604094

**Comment by ROBERT-MCDOWELL** [comment]
Please reopen if it persists.
