### ISSUE TITLE
Container Size on Unraid

### ISSUE THREAD

**Issue by KyleJFellin** [DrewThomasson/ebook2audiobook#162]
![Screenshot from 2024-12-29 19-58-54](https://github.com/user-attachments/assets/44cceb3c-1de0-487f-b013-f4ab68d5d578)
Container size on Unraid is nearly 30GB. Any advice for offloading some of this to the array vs the docker image?

**Comment by AzrelixJ** [comment]
> ![Screenshot from 2024-12-29 19-58-54](https://private-user-images.githubusercontent.com/66495629/399196495-44cceb3c-1de0-487f-b013-f4ab68d5d578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MjgwNjMsIm5iZiI6MTczNTUyNzc2MywicGF0aCI6Ii82NjQ5NTYyOS8zOTkxOTY0OTUtNDRjY2ViM2MtMWRlMC00ODdmLWIwMTMtZjRhYjY4ZDVkNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDAzMDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MGM5YTVmNTI1Yzg5Y2Q2OWU0ZWI0YmY4ZDdmZDZmYjQzNTE3OTUyMTE5NTA0MzM4ZjdjNTJiMjgzYWY3ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HJ-4e8u8d93EMHpmv2GP4GU28_uAYjaxkNEJLisGy7M) Container size on Unraid is nearly 30GB. Any advice for offloading some of this to the array vs the docker image?

I was wondering the same thing, hoping that most of this can be saved the app drive in the main array instead of the docker image.

**Comment by DrewThomasson** [comment]
no idea about the unraid someone out there made it out of the existing ebook2audiobook docker image

If I were to guess though Have you selected multiple fine-tuned models so far?

Cause they are saved to the models folder after you use each fine-tuned voice from the dropdown

So check the size of the models folder, I'm curious...

**Comment by janstadt** [comment]
@DrewThomasson I think we should map your volumes to local drives instead of storing it all in your container.

**Comment by DrewThomasson** [comment]
So I should set it to the folder the 'docker-compose.yml' is located in right?

like this?

```

volumes:
  - ./:/home/user/app
```

**Comment by DrewThomasson** [comment]
cause the `app` dir is just a dir containing the ebook2audiobook git main repo anyway

**Comment by janstadt** [comment]
Correct, the left hand of the volume is on your host and can be wherever you want. This will allow that content to be outside of the container. I thought about doing the models and voices folders specifically since those are the beefy directories, but i ended up just doing the entire app directory.

**Comment by DrewThomasson** [comment]
kk I'll add that to the existing docker-compose.yml

**Comment by DrewThomasson** [comment]
Just added to the `docker-compose.yml`👌 
@janstadt

**Comment by DrewThomasson** [comment]
gona try a test on my end with it

hit me up if you have any issue with the new update 

@janstadt

**Comment by DrewThomasson** [comment]
hm changed it to a optional comment you can "uncomment" in the `docker-compose.yml` because some people are running into permission issues

**Comment by janstadt** [comment]
Yeah typically when u mount volumes youll need to pass user and group ids in the env vars. Im curious if you can also clean up the repo after whatever artifact/binary is built to save space as well.

**Comment by DrewThomasson** [comment]
Hm

Interesting...

I didn't know about any of this, still pretty new at docker tbh

**Comment by DrewThomasson** [comment]
@janstadt 

Do you think you might be able to help me build the Dockerfile

Cause right now it's been broken and I can figure this out :/

**Comment by janstadt** [comment]
I'll take a quick look

**Comment by DrewThomasson** [comment]
@janstadt 

Thx lol

Heres where my latest broken `Dockerfile`attempt is located

https://github.com/DrewThomasson/ebook2audiobook/blob/v2.0_Dockerfile/Dockerfile

but I would really like to be able to just have it launch the `ebook2audiobook.sh` 

At the moment the current image is built by just pulling this hugginface as a docker image
https://huggingface.co/spaces/drewThomasson/ebook2audiobook_v2.0_Beta

which isn't ideal 😅

**Comment by VlarpNL** [comment]
I'm running into the same issue and was already trying to work this out on my own. Happy to see people are already working on solving this :)

**Comment by jaycedk** [comment]
When trying to fix my docker image / container size issues, so it does not run out of space.
I converted my docker vDisk into a folder on my Nvme, where the vDisk also is.
This will not save space, you just don't have to run out of space in your vDisk.

In unRaid goto setttings -> docker -> stop docker edit from vDisk to library.

**_**Warring**_ **

Doing this you will have to recreate all you dockers.
That is done, from the docker tab, at the button "Add container" and select your template.
It should keep all your settings, when done this way.

But it would like not having to do this.
So a fix would be appreciated.

Happy New Years, to you all 🎆🎇

**Comment by DrewThomasson** [comment]
Got a fully working `Dockerfile` now so 

That should make it easier to workout more of this stuff...

**Comment by DrewThomasson** [comment]
So does the new `Volumes` line you can activate  in the docker-compose link it to the repo dir works for everyone here?

if so I'm closing out this issue 👍

**Comment by janstadt** [comment]
It looks like you moved from the ~/app directory to ~/ebook2audiobook which is totally fine. I think i figured out why the volumes werent being mounted properly though. Since you're entrypoint is being fed the CMD (`python app.py`) from your Dockerfile and the app pulls things down every time it starts the app, when i was mapping my volume to the root, it was expecting things to be there (like the app.py file itself), but since my host directory didnt have anything in it, it would fail. Essentially you're not supposed to map the entire working dir as a vol so i can map subdirectories and that works fine, but i still see something odd going on. 

In the dockerfile you run pip install requirements.txt which includes unidic, but then in the app.py here: https://github.com/DrewThomasson/ebook2audiobook/blob/main/app.py#L61 it checks for unidic and it doesnt find it so it redownloads it which takes a while to get done (its over a gb) so i wonder why thats happening? Shouldnt pip install that via the dockerfile and requirements.txt? Is it because you're passing `--no-cache-dir`? I think thats correct since you want to keep your container as small as possible, but im not a python dev.

Finally, permissions are always a pain in docker and the dockerd will run as root on the host server and typically will write mapped volumes as root which causes all sorts of permissioning issues. i thought you could pass `-u 1000:1000` to tell the dockerd to run as the current user, but it still creates the volumes incorrectly. If they exist beforehand and are owned by a non root user, they'll stay like that, but there are other dockerfiles that somehow manage to create the volumes as the user when passed the PGID and GUID but i think it has more to do with the fact that they map a known volume in the container where they typically store configs and data that needs to be preserved between restarts. the linuxserver dockerfiles are a good example of allowing a user to map a config directory where all the persistent stuff can be put (dbs, configs, outputs, etc) https://github.com/linuxserver/docker-swag/blob/master/Dockerfile#L188 and then allow a user to run the container under a known host user via environment variables like this: https://github.com/linuxserver/docker-swag/tree/master?tab=readme-ov-file#docker-compose-recommended-click-here-for-more-info

Foof, thats a long post.....

**Comment by citadella** [comment]
Can someone give me a final update on where this sits/what we can do to mitigate the issue? Because the unraid app (docker template) appears to be from the initial release on December 27th, which didn't work and I'm not really clear on how to get this setup correctly based on the above comments so I'm (hopefully) waiting for an update to that docker template...

**Comment by citadella** [comment]
Right, thanks, think this did it for me!

**Comment by citadella** [comment]
Well...workeed, but unRAID still crashed. No idea what for, though, but definitely related to this (the only thing I've added in months)

**Comment by janstadt** [comment]
You can spin down your array and edit your docker settings to expand your docker.img file. Seems like its still pulling down things inside the container when it starts that would be great to have that located elsewhere or mounted on the host.

**Comment by DrewThomasson** [comment]
> It looks like you moved from the ~/app directory to ~/ebook2audiobook which is totally fine. I think i figured out why the volumes werent being mounted properly though. Since you're entrypoint is being fed the CMD (`python app.py`) from your Dockerfile and the app pulls things down every time it starts the app, when i was mapping my volume to the root, it was expecting things to be there (like the app.py file itself), but since my host directory didnt have anything in it, it would fail. Essentially you're not supposed to map the entire working dir as a vol so i can map subdirectories and that works fine, but i still see something odd going on.
> 
> In the dockerfile you run pip install requirements.txt which includes unidic, but then in the app.py here: https://github.com/DrewThomasson/ebook2audiobook/blob/main/app.py#L61 it checks for unidic and it doesnt find it so it redownloads it which takes a while to get done (its over a gb) so i wonder why thats happening? Shouldnt pip install that via the dockerfile and requirements.txt? Is it because you're passing `--no-cache-dir`? I think thats correct since you want to keep your container as small as possible, but im not a python dev.
> 
> Finally, permissions are always a pain in docker and the dockerd will run as root on the host server and typically will write mapped volumes as root which causes all sorts of permissioning issues. i thought you could pass `-u 1000:1000` to tell the dockerd to run as the current user, but it still creates the volumes incorrectly. If they exist beforehand and are owned by a non root user, they'll stay like that, but there are other dockerfiles that somehow manage to create the volumes as the user when passed the PGID and GUID but i think it has more to do with the fact that they map a known volume in the container where they typically store configs and data that needs to be preserved between restarts. the linuxserver dockerfiles are a good example of allowing a user to map a config directory where all the persistent stuff can be put (dbs, configs, outputs, etc) https://github.com/linuxserver/docker-swag/blob/master/Dockerfile#L188 and then allow a user to run the container under a known host user via environment variables like this: https://github.com/linuxserver/docker-swag/tree/master?tab=readme-ov-file#docker-compose-recommended-click-here-for-more-info
> 
> Foof, thats a long post.....

oh yeah forgot to post here in response to this...

1. The file structure In the compose and the Dockerfile in the repo now both reference ~/app and not ~/ebook2audiobook so that should fix that part

2. I also added comments in the Dockerfile that will make the Dockerfile run through a test.txt file so then the unidict and base model will be baked into the image you make form it, if un-commented that is :)

**Comment by citadella** [comment]
I completely removed the image, created the directories, and re-added it with the custom mappings and confirmed files were going into those respective directories. Then I locked down the CPUs to only 3/8. But still, after about 3-4h, my unRAID completely locked up. Unfortunately I don't run an outside syslog server so I don't know why-I could still see port 22 open, but couldn't even connect to that to get in to see so had to just reboot it.

**Comment by nwithan8** [comment]
@VlarpNL @DrewThomasson I'm the maintainer of the Unraid template for this app. Apologies for all the issues that have arisen, was going off the Docker Compose file available at the time. Would love to update the template accordingly, just let me know when everything is in a working state and I can translate a Docker Compose into the Unraid template.

**Comment by DrewThomasson** [comment]
Hey @nwithan8! 😁

So the current state of the compose and Dockefile file should be stable now

With the directory structure and such

I'll hit u up if there's any major changes tho

We're working on v2.1 rn which fixes a lota bugs

**Comment by leptoid** [comment]
> For now I've used the Unraid template (don't think that is absolutely necessary but it's a bit easier), but during the Add Container part I changed the Repository to athomasson2/ebook2audiobook:latest
> 
> I then added 3 Path mounts: /home/user/app/tmp > /mnt/user/appdata/ebook2audiobook/app/tmp/ /home/user/app/audiobooks > /mnt/user/appdata/ebook2audiobook/app/audiobooks/ /home/user/app/models > /mnt/user/appdata/ebook2audiobook/app/models/
> 
> Make sure that you create these directories first before starting the container! I did that using Midnight Commander because I'm lazy and no Linux wizard. Then after you did that use chown to change the owner of /mnt/user/appdata/ebook2audiobook/app and it's subdirectories so the permissions are correct: chown 1000:1000 -R /mnt/user/appdata/ebook2audiobook/app/ (do this from within Unraid)
> 
> After this you should be able to Apply the container settings and start the container.
> 
> This at least gets some of the more data heavy parts outside of the docker.img
> 
> ![image](https://private-user-images.githubusercontent.com/95382892/399687383-c36e720a-9cac-454f-955c-32681953976b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3MjAxNDMsIm5iZiI6MTczNjcxOTg0MywicGF0aCI6Ii85NTM4Mjg5Mi8zOTk2ODczODMtYzM2ZTcyMGEtOWNhYy00NTRmLTk1NWMtMzI2ODE5NTM5NzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEyVDIyMTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjhmZTA0NTNjZmFlZjYyMjZhMTQwYWZhZDQ5NzRlMDlmOThmNzg3YTRkZmFjYTZmMzFlMjdmMTliYjc5YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wc-PHCN7X-9QOVp4loc7yZxZTg4fcjjvzM9L5Xya1MU)
> 
> edit: This is not the right way to solve this issue though. This is just a dirty workaround. I hope Drew and others are able to solve this in a nice way :).

This worked for me whereas nothing else did.  Thank you.

**Comment by gamegoofs2** [comment]
Hi all,

I followed @VlarpNL advice. I changed the repo to athomasson2/ebook2audiobook:lastest, created the volume paths with permissions for 1000:1000, and added the paths to the container. However, when I run the container I still get:

`python: can't open file '/home/user/app/app.py': [Errno 2] No such file or directory`

My Unraid server is the only computer with an actual GPU in it. So it would be ideal if I can get this running on there.

Any help is greatly appreciated.

**Comment by citadella** [comment]
I've switched to using https://github.com/aedocw/epub2tts-edge 

It's not perfect, and the voices are far worse, but it requires next to no CPU utilization...

**Comment by ROBERT-MCDOWELL** [comment]
ebook2audiobook uses CPU or GPU, if you have some issue using your GPU check the python torch cuda version installed in your docker and adapt it to your GPU

**Comment by babanovac1980** [comment]
> For now I've used the Unraid template (don't think that is absolutely necessary but it's a bit easier), but during the Add Container part I changed the Repository to athomasson2/ebook2audiobook:latest
>  I then added 3 Path mounts: /home/user/app/tmp > /mnt/user/appdata/ebook2audiobook/app/tmp/ /home/user/app/audiobooks > /mnt/user/appdata/ebook2audiobook/app/audiobooks/ /home/user/app/models > /mnt/user/appdata/ebook2audiobook/app/models/
>     Make sure that you create these directories first before starting the container! I did that using Midnight Commander because I'm lazy and no Linux wizard. Then after you did that use chown to change the owner of /mnt/user/appdata/ebook2audiobook/app and it's subdirectories so the permissions are correct: chown 1000:1000 -R /mnt/user/appdata/ebook2audiobook/app/ (do this from within Unraid)
> After this you should be able to Apply the container settings and start the container.
> This at least gets some of the more data heavy parts outside of the docker.img
>     edit: This is not the right way to solve this issue though. This is just a dirty workaround. I hope Drew and others are able to solve this in a nice way :).

I did exactly the same but I still get:

`python: can't open file '/home/user/app/app.py': [Errno 2] No such file or directory`

I really need it to run on my Unraid server as I have 2 Nvidia P40 on it just for AI purposes.
Any other suggestions?

Thanks

**Comment by nwithan8** [comment]
Hey all, sorry it took me so long to weigh in and address these issues with the Unraid template.

It looks like the original Docker container that the template points to has since been deprecated and replaced with a new one, the source code for which still uses this GitHub repo. So I was getting confused about why the Dockerfiles in here were acting differently when used on Unraid 🤦🏻 

I've updated the existing template to indicate that it's the legacy (read: non-working) version, and I'm working on releasing a new template that will work with the path mappings and such that work in the new Docker image.

@babanovac1980 I thought the issue with your template was the use of the "Files Path" that was deprecated a few weeks ago, but in my investigation, it seems there's been even more deprecation that still would cause other issues. For you (and everyone), it's going to be best to simply uninstall that existing template (you can also delete the image in the process; it's not going to be used going forward), and install the new "ebooks2audiobook" template from the Community Apps store once it's available in a few hours.

The new image that it uses also seems to be a bit smaller, and with the proper models host-container path mapping, the overall image size should be much more manageable now.

**Comment by babanovac1980** [comment]
> @babanovac1980 I thought the issue with your template was the use of the "Files Path" that was deprecated a few weeks ago, but in my investigation, it seems there's been even more deprecation that still would cause other issues. For you (and everyone), it's going to be best to simply uninstall that existing template (you can also delete the image in the process; it's not going to be used going forward), and install the new "ebooks2audiobook" template from the Community Apps store once it's available in a few hours.

Thank you!

**Comment by DrewThomasson** [comment]
> Hey all, sorry it took me so long to weigh in and address these issues with the Unraid template.
> 
> It looks like the original Docker container that the template points to has since been deprecated and replaced with a new one, the source code for which still uses this GitHub repo. So I was getting confused about why the Dockerfiles in here were acting differently when used on Unraid 🤦🏻 
> 
> I've updated the existing template to indicate that it's the legacy (read: non-working) version, and I'm working on releasing a new template that will work with the path mappings and such that work in the new Docker image.
> 
> @babanovac1980 I thought the issue with your template was the use of the "Files Path" that was deprecated a few weeks ago, but in my investigation, it seems there's been even more deprecation that still would cause other issues. For you (and everyone), it's going to be best to simply uninstall that existing template (you can also delete the image in the process; it's not going to be used going forward), and install the new "ebooks2audiobook" template from the Community Apps store once it's available in a few hours.
> 
> The new image that it uses also seems to be a bit smaller, and with the proper models host-container path mapping, the overall image size should be much more manageable now.
> 
> @DrewThomasson do you know if the container respects PUID and PGID environmental variables? Running into a flaky permissions error when trying to write to the mapped models folder. On Unraid, folders, including those auto-generated during Docker container installation, are `nobody:users` with `99:100` PUID/PGID, but it seems like this container runs on its own `root` user with `1000:1000`.


I actually don't know.... I know had to have it create a user that's separate from the root in order to get it to run in hugging face spaces...

You can see the Dockerfile used to build the image in the repo here tho

https://github.com/DrewThomasson/ebook2audiobook/blob/main/Dockerfile

**Comment by babanovac1980** [comment]
I installed it from the new template and not at least the container starts. However I get these in the logs:
`There was a problem when trying to write in your cache folder (/home/user/app/models). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
mkdir -p failed for path /home/user/app/models/matplotlib: [Errno 13] Permission denied: '/home/user/app/models/matplotlib'
Matplotlib created a temporary cache directory at /tmp/matplotlib-7bvqw2bb because there was an issue with the default path (/home/user/app/models/matplotlib); it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.`

And then when I start the web ui:
`Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/gradio/queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/gradio/blocks.py", line 2047, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/gradio/blocks.py", line 1594, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/gradio/utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/user/app/lib/functions.py", line 1471, in change_gr_read_data
    os.makedirs(session['custom_model_dir'], exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/user/app/models/__sessions'`

**Comment by DrewThomasson** [comment]
> "PermissionError: [Errno 13] Permission denied: '/home/user/app/models/__sessions", try "root" user

Agreed

**Comment by Sverte** [comment]
> `python: can't open file '/home/user/app/app.py': [Errno 2] No such file or directory`

I removed python app.py from the post arguments and it started the container fine for me.

**Comment by ROBERT-MCDOWELL** [comment]
the nee docker does not need "python app.py", you confirm @DrewThomasson ?

**Comment by DrewThomasson** [comment]
> the nee docker does not need "python app.py", you confirm [@DrewThomasson](https://github.com/DrewThomasson) ? maybe this note: should be written in the docker compose or elsewhere?

Yes confirmed,  I swapped out the `CMD` for `ENTRYPOINT` so now all CMD will be appended to the end of the `ENTRYPOINT` command

so instead of having to do `python app.py ect.....`

it's just  `extra parameters here` for instance `--help`

**Comment by DrewThomasson** [comment]
> > `python: can't open file '/home/user/app/app.py': [Errno 2] No such file or directory`
> 
> I removed python app.py from the post arguments and it started the container fine for me.

In short yes, No post arguments are needed anymore 👍

**Comment by ROBERT-MCDOWELL** [comment]
@nwithan8 maybe we can manage worflow for it, because for now we are fixing bugs every week until to reach a stable version.

**Comment by DrewThomasson** [comment]
@nwithan8 
@ROBERT-MCDOWELL 
True

Ill, go close the other unraid issues

and @ you if more unraid bugs come up 👍

**Comment by DrewThomasson** [comment]
Closing this issue, if issue persists re-open

**Comment by ROBERT-MCDOWELL** [comment]
ok sounds good

**Comment by nwithan8** [comment]
> @nwithan8 maybe we can manage a worflow for it? because for now we are fixing bugs every week until to reach a stable version.

Sure thing. If you want to host the template in your own repo and [establish yourself as a contributor to the Unraid community apps store](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084), I'll gladly deprecated the version in my repo (remove it from the store) and make yours the official version.

If you don't want to go through that hassle, I'm always open to updating the template in my repo, if you want to establish some automated/manual workflow for that.

**Comment by ROBERT-MCDOWELL** [comment]
> > [@nwithan8](https://github.com/nwithan8) maybe we can manage a worflow for it? because for now we are fixing bugs every week until to reach a stable version.
> 
> Sure thing. If you want to host the template in your own repo and [establish yourself as a contributor to the Unraid community apps store](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084), I'll gladly deprecated the version in my repo (remove it from the store) and make yours the official version.
> 
> If you don't want to go through that hassle, I'm always open to updating the template in my repo, if you want to establish some automated/manual workflow for that.

I guess you have already a workflow for it no? dunno if you can fork our main repo then find a way to run your own workflow that feed your store directly....

**Comment by nwithan8** [comment]
I don't currently have a workflow, have been maintaining all the templates manually whenever there's a change to environmental variables. Have been planning a way to automate it though, some way of monitoring the various apps and e.g. alerting me/opening a GitHub issue if the Docker Compose file changes, and maybe even automatically generating templates from a Docker Compose file. This will definitely become one of the first to test said process once it's up and running.
