### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'

### ISSUE THREAD

**Issue by alexanderjacuna** [DrewThomasson/ebook2audiobook#284]
### Summary:
When converting an example text file using a custom model the conversion is immediately "cancelled". Terminal outputs the following error: AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'. This is the same error seen in DrewThomasson/ebook2audiobook#278 but was noted as fixed. Still seeing this issue so making a dedicated issue for it. Please ignore if addressed already, but wanted to create an issue because I am still seeing this after pulling. Using WSL for this test.

**Setup:**
Run git pull
```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook$ git pull
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 61 (delta 33), reused 27 (delta 13), pack-reused 0 (from 0)
Unpacking objects: 100% (61/61), 15.42 KiB | 47.00 KiB/s, done.
From https://github.com/DrewThomasson/ebook2audiobook
   e60ca88..ef9e69a  main                 -> origin/main
 * [new branch]      Selenium_GUI_testing -> origin/Selenium_GUI_testing
Updating e60ca88..ef9e69a
Fast-forward
 ebook2audiobook.cmd        | 67 ++++++++++++++++++++++++++++++-------------------------------------
 lib/classes/tts_manager.py | 14 +++++++-------
 lib/functions.py           | 18 +++++++++++++-----
 3 files changed, 50 insertions(+), 49 deletions(-)
```

**Steps to reproduce:**
1. Run script 'ebook2audiobook.sh' & wait for webui.
2. Webui loads.
3. Upload custom_model.zip. ---> SUCCEEDS
4. Select "custom_model" from dropdown.
5. Upload test.txt file. ---> SUCCEEDS
6. Click the bottom ebook emojii to start conversion.
7. Almost immediately the conversion is 'cancelled' via a notification in the webui.

**Terminal output:**
```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook$ ./ebook2audiobook.sh
Running in native mode
IPs available for connection:
['127.0.0.1', '::1', '172.25.97.126', 'fe80::215:5dff:feaa:2754%eth0']
Note: 0.0.0.0 is not the IP to connect. Instead use an IP above to connect.
* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

Extracted files to /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987/xtts/custom_model
Processing eBook file: test.txt
Available Processor Unit: cuda
Running command: /usr/bin/ebook-convert /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/test.txt /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/__test.epub --input-encoding=utf-8 --output-profile=generic_eink --verbose
Conversion options changed from defaults:
  output_profile: 'generic_eink'
  verbose: 1
  input_encoding: 'utf-8'
1% Converting input to HTML...
InputFormatPlugin: TXT Input running
on /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/test.txt
Reading text from file...
Using user specified input encoding of utf-8
Auto detected paragraph type as single
Auto detected formatting as heuristic
Running text through basic conversion...
Language not specified
Creator not specified
Building file list...
        Found files...
                 HTMLFile:0:a:'/mnt/c/Users/Alexander/ebook2audiobook/tmp/calibre_7.6.0_tmp_0ub5epf_/hzupxxyn_plumber/index.html'
Normalizing filename cases
Rewriting HTML links
Parsing index.html ...
*********  Heuristic processing HTML  *********
flow is too short, not running heuristics
Forcing index.html into XHTML namespace
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1 items of level: p_1
Ignoring level p_1
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Running EPUB Output plugin
Splitting markup on page breaks and flow limits, if any...
        Looking for large trees in index.html...
        No large trees found
Generating default cover
This EPUB file has no Table of Contents. Creating a default TOC
EPUB output written to /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/__test.epub
Output saved to   /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/__test.epub

/mnt/c/Users/Alexander/ebook2audiobook/python_env/lib/python3.12/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
******* NOTE: YOU CAN SAFELY IGNORE "Character xx not found in the vocabulary." *******
Loading TTS xtts model from /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987/xtts/custom_model, it takes a while, please be patient...
coqui_tts_load_custom() error: Xtts.load_checkpoint() got an unexpected keyword argument 'enable_deepspeed'
convertsion 0.00%: 0/1 Part 1 containing 1 sentences...
Computing speaker latents...
convertsion 0.00%: 0/1
'NoneType' object has no attribute 'get_conditioning_latents'
Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 167, in convert_sentence_to_audio
    self.params['gpt_cond_latent'], self.params['speaker_embedding'] = self.params['tts'].get_conditioning_latents(audio_path=[self.params['voice_path']])
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/functions.py", line 675, in convert_chapters_to_audio
    if tts_manager.convert_sentence_to_audio():
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 286, in convert_sentence_to_audio
    raise ValueError(e)
ValueError: 'NoneType' object has no attribute 'get_conditioning_latents'
Caught DependencyError: 'NoneType' object has no attribute 'get_conditioning_latents'
convert_chapters_to_audio() failed!
```

**Comment by alexanderjacuna** [comment]
I was able to reproduce this error using a legit epub instead of a generic text file with a couple words in it. Wanted to try and rule out if it was something to do with the overly simple text file I've been testing with.


**Using a legit epub file:**
```
Processing eBook file: Fifty-Shades-of-Grey.epub
Available Processor Unit: cuda
Running command: /usr/bin/ebook-convert /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/beea48da41865a17e18b9f7f2fd581cd/Fifty-Shades-of-Grey.epub /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/beea48da41865a17e18b9f7f2fd581cd/__Fifty-Shades-of-Grey.epub --input-encoding=utf-8 --output-profile=generic_eink --verbose
Conversion options changed from defaults:
  verbose: 1
  input_encoding: 'utf-8'
  output_profile: 'generic_eink'
1% Converting input to HTML...
InputFormatPlugin: EPUB Input running
on /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/beea48da41865a17e18b9f7f2fd581cd/Fifty-Shades-of-Grey.epub
Found HTML cover OEBPS/Text/titlepage.xhtml
Parsing all content...
Parsing OEBPS/Text/index_split_005.html ...
Parsing OEBPS/Text/index_split_006.html ...
Parsing OEBPS/Text/index_split_008.html ...
Parsing OEBPS/Text/index_split_010.html ...
Parsing OEBPS/Text/index_split_012.html ...
Parsing OEBPS/Text/index_split_016.html ...
Parsing OEBPS/Text/index_split_018.html ...
Parsing OEBPS/Text/index_split_020.html ...
Parsing OEBPS/Styles/stylesheet.css ...
Parsing OEBPS/Text/Section0001.xhtml ...
Parsing OEBPS/Text/index_split_002.html ...
Parsing OEBPS/Text/index_split_014.html ...
Parsing OEBPS/Text/index_split_004.html ...
Parsing OEBPS/Text/index_split_007.html ...
Parsing OEBPS/Text/index_split_009.html ...
Parsing OEBPS/Text/index_split_011.html ...
Parsing OEBPS/Text/index_split_015.html ...
Parsing OEBPS/Text/index_split_013.html ...
Parsing OEBPS/Text/index_split_017.html ...
Parsing OEBPS/Text/index_split_019.html ...
Parsing OEBPS/Text/index_split_001.html ...
Parsing OEBPS/Text/index_split_000.html ...
Parsing OEBPS/Text/index_split_003.html ...
Parsing OEBPS/Text/titlepage.xhtml ...
Reading TOC from NCX...
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 2512 items of level: p_1
p_1  left margin stats: Counter({'0': 2512})
p_1  right margin stats: Counter({'0': 2512})
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Running EPUB Output plugin
Splitting markup on page breaks and flow limits, if any...
        Looking for large trees in OEBPS/Text/index_split_005.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_006.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_008.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_010.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_012.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_016.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_018.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_020.html...
        No large trees found
        Looking for large trees in OEBPS/Text/Section0001.xhtml...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_002.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_014.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_004.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_007.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_009.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_011.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_015.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_013.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_017.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_019.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_001.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_000.html...
        No large trees found
        Looking for large trees in OEBPS/Text/index_split_003.html...
        No large trees found
EPUB output written to /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/beea48da41865a17e18b9f7f2fd581cd/__Fifty-Shades-of-Grey.epub
Output saved to   /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/beea48da41865a17e18b9f7f2fd581cd/__Fifty-Shades-of-Grey.epub

/mnt/c/Users/Alexander/ebook2audiobook/python_env/lib/python3.12/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
******* NOTE: YOU CAN SAFELY IGNORE "Character xx not found in the vocabulary." *******
Loading TTS xtts model from /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987/xtts/custom_model, it takes a while, please be patient...
coqui_tts_load_custom() error: Xtts.load_checkpoint() got an unexpected keyword argument 'enable_deepspeed'
convertsion 0.00%: 0/4639 Part 1 containing 13 sentences...
Computing speaker latents...
convertsion 0.00%: 0/4639
'NoneType' object has no attribute 'get_conditioning_latents'
Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 167, in convert_sentence_to_audio
    self.params['gpt_cond_latent'], self.params['speaker_embedding'] = self.params['tts'].get_conditioning_latents(audio_path=[self.params['voice_path']])
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/functions.py", line 675, in convert_chapters_to_audio
    if tts_manager.convert_sentence_to_audio():
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 286, in convert_sentence_to_audio
    raise ValueError(e)
ValueError: 'NoneType' object has no attribute 'get_conditioning_latents'
Caught DependencyError: 'NoneType' object has no attribute 'get_conditioning_latents'
convert_chapters_to_audio() failed!
```

**Comment by ROBERT-MCDOWELL** [comment]
it seems you already add a comment on this issue from the #278

**Comment by alexanderjacuna** [comment]
> it seems you already add a comment on this issue from the [#278](https://github.com/DrewThomasson/ebook2audiobook/issues/278)

Yep, still seeing the issue so I created a new one. Didn't want to double dip with the first issue actually being two different issues.

**Comment by ROBERT-MCDOWELL** [comment]
ok better.

**Comment by ROBERT-MCDOWELL** [comment]
could you run it in headless mode?
so it should be
./ebook2audiobook --ebook /path/to/file --custom_model /path/to/model.zip --tts_engine xtts --device gpu

btw, could you tell me which cuda you have installed and which GPU?
seems you are the one who has the GPU working....

**Comment by alexanderjacuna** [comment]
Here is the output of nvidia-smi, which shows my setup as using cuda 12.8.

```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook/tools$ nvidia-smi
Sun Feb 16 11:39:12 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.16              Driver Version: 572.16         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:2B:00.0  On |                  N/A |
|  0%   41C    P8             25W /  370W |    1589MiB /  24576MiB |     11%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by alexanderjacuna** [comment]
Git pulling
```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook$ git pull
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 3.51 KiB | 171.00 KiB/s, done.
From https://github.com/DrewThomasson/ebook2audiobook
   ef9e69a..74be3d7  main       -> origin/main
Updating ef9e69a..74be3d7
Fast-forward
 Dockerfile | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)
```

Running headless with requested options
```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook$ ./ebook2audiobook.sh \
> --headless \
> --ebook /mnt/c/Users/Alexander/ebook2audiobook/test.txt \
> --custom_model /mnt/c/Users/Alexander/ebook2audiobook/custom_model.zip \
> --device gpu \
> --tts_engine xtts \
> --language eng
Running in native mode
100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:27<00:00,  6.96s/files]
Extracted files to /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-89d4f909-890b-4894-b30e-1eb58df98f52/xtts/custom_model
Available Processor Unit: cuda
Running command: /usr/bin/ebook-convert /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-89d4f909-890b-4894-b30e-1eb58df98f52/1a200d796fbe8c3cda9d9d56d4498565/test.txt /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-89d4f909-890b-4894-b30e-1eb58df98f52/1a200d796fbe8c3cda9d9d56d4498565/__test.epub --input-encoding=utf-8 --output-profile=generic_eink --verbose
Conversion options changed from defaults:
  verbose: 1
  input_encoding: 'utf-8'
  output_profile: 'generic_eink'
1% Converting input to HTML...
InputFormatPlugin: TXT Input running
on /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-89d4f909-890b-4894-b30e-1eb58df98f52/1a200d796fbe8c3cda9d9d56d4498565/test.txt
Reading text from file...
Using user specified input encoding of utf-8
Auto detected paragraph type as single
Auto detected formatting as heuristic
Running text through basic conversion...
Language not specified
Creator not specified
Building file list...
        Found files...
                 HTMLFile:0:a:'/mnt/c/Users/Alexander/ebook2audiobook/tmp/calibre_7.6.0_tmp_6z1x5g62/w5gu3do4_plumber/index.html'
Normalizing filename cases
Rewriting HTML links
Parsing index.html ...
*********  Heuristic processing HTML  *********
flow is too short, not running heuristics
Forcing index.html into XHTML namespace
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1 items of level: p_1
Ignoring level p_1
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Running EPUB Output plugin
Splitting markup on page breaks and flow limits, if any...
        Looking for large trees in index.html...
        No large trees found
Generating default cover
This EPUB file has no Table of Contents. Creating a default TOC
EPUB output written to /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-89d4f909-890b-4894-b30e-1eb58df98f52/1a200d796fbe8c3cda9d9d56d4498565/__test.epub
Output saved to   /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-89d4f909-890b-4894-b30e-1eb58df98f52/1a200d796fbe8c3cda9d9d56d4498565/__test.epub

/mnt/c/Users/Alexander/ebook2audiobook/python_env/lib/python3.12/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
******* NOTE: YOU CAN SAFELY IGNORE "Character xx not found in the vocabulary." *******
Loading TTS xtts model from custom_model, it takes a while, please be patient...
coqui_tts_load_custom() error: [Errno 2] No such file or directory: '/mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-89d4f909-890b-4894-b30e-1eb58df98f52/custom_model/config.json'
convertsion 0.00%: 0/1 Part 1 containing 1 sentences...
Computing speaker latents...
convertsion 0.00%: 0/1
'NoneType' object has no attribute 'get_conditioning_latents'
Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 167, in convert_sentence_to_audio
    self.params['gpt_cond_latent'], self.params['speaker_embedding'] = self.params['tts'].get_conditioning_latents(audio_path=[self.params['voice_path']])
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/functions.py", line 675, in convert_chapters_to_audio
    if tts_manager.convert_sentence_to_audio():
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 286, in convert_sentence_to_audio
    raise ValueError(e)
ValueError: 'NoneType' object has no attribute 'get_conditioning_latents'
Caught DependencyError: 'NoneType' object has no attribute 'get_conditioning_latents'
```

**Comment by ROBERT-MCDOWELL** [comment]
ok here is the issue: /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-89d4f909-890b-4894-b30e-1eb58df98f52/custom_model/config.json

could you check the folder?
ls -l /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-89d4f909-890b-4894-b30e-1eb58df98f52/custom_model/

**Comment by alexanderjacuna** [comment]
```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook$ ls -l /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-89d4f909-890b-4894-b30e-1eb58df98f52/custom_model/
ls: cannot access '/mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-89d4f909-890b-4894-b30e-1eb58df98f52/custom_model/': No such file or directory
```

![Image](https://github.com/user-attachments/assets/8a093732-4a25-4ce6-90d1-97ce7db2bcf8)

**Comment by ROBERT-MCDOWELL** [comment]
something blocked the extraction or else. if unzip failed it should be another raise error...

**Comment by ROBERT-MCDOWELL** [comment]
btw what's inside xtts folder?

**Comment by alexanderjacuna** [comment]
> btw what's inside xtts folder?

![Image](https://github.com/user-attachments/assets/8f3d63e1-716a-4b40-b060-645301e0dccd)

![Image](https://github.com/user-attachments/assets/87578430-9254-4569-9f45-6219da338a23)

**Comment by alexanderjacuna** [comment]
Btw I do have the working directory excluded from AV scanning. So we can rule out the AV whacking files during extraction.

![Image](https://github.com/user-attachments/assets/cf881940-7b77-44c3-8172-3aab2463ceca)

**Comment by ROBERT-MCDOWELL** [comment]
ok I see, it's missing the tts_engine folder in the path, I'm fixing it now.

**Comment by irememoryi** [comment]
> ok I see, it's missing the tts_engine folder in the path, I'm fixing it now.

pls

**Comment by alexanderjacuna** [comment]
I can confirm this also happens with the dockerhub image.

`athomasson2/ebook2audiobook:74be3d717`

**Comment by DrewThomasson** [comment]
@alexanderjacuna 

Confirmed fixed now?

If so I'll rebuild the docker image again

**Comment by ROBERT-MCDOWELL** [comment]
@DrewThomasson it should be but need some returns.

**Comment by DrewThomasson** [comment]
Kk I'll wait 👍

**Comment by alexanderjacuna** [comment]
Still seeing the issue unfortunately. I tried with both a sample text file and a full epub same result. Actually seeing both of these still:

- DrewThomasson/ebook2audiobook#284 coqui_tts_load_custom() error: Xtts.load_checkpoint() got an unexpected keyword argument 'enable_deepspeed'
- DrewThomasson/ebook2audiobook#278 AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'


**Git pull**
```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook$ git pull
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 19 (delta 10), reused 14 (delta 9), pack-reused 0 (from 0)
Unpacking objects: 100% (19/19), 12.49 KiB | 96.00 KiB/s, done.
From https://github.com/DrewThomasson/ebook2audiobook
   c32efe6..7b776ef  main         -> origin/main
 * [new branch]      readmeUpdate -> origin/readmeUpdate
Updating c32efe6..7b776ef
Fast-forward
 Mac Ebook2Audiobook Launcher.command |   2 +-
 ebook2audiobook.cmd                  | 221 ++++++++++++++++++++++++++++++++++++++++-----------------------------------
 ebook2audiobook.sh                   |  19 -------
 lib/classes/tts_manager.py           |   6 +--
 lib/conf.py                          |  14 ++---
 5 files changed, 129 insertions(+), 133 deletions(-)
```

**Starting up**
```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook$ ./ebook2audiobook.sh
Running in native mode

IPs available for connection:
['127.0.0.1', '::1', '172.25.97.126', 'fe80::215:5dff:feaa:28d9%eth0']
Note: 0.0.0.0 is not the IP to connect. Instead use an IP above to connect.
* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
```


**Executing model upload, text/epud upload, selecting model, click convert**
```
100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:18<00:00,  4.67s/files]
Extracted files to /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987/xtts/model
Processing eBook file: test.txt
Available Processor Unit: cuda
Running command: /usr/bin/ebook-convert /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/test.txt /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/__test.epub --input-encoding=utf-8 --output-profile=generic_eink --verbose
Conversion options changed from defaults:
  verbose: 1
  output_profile: 'generic_eink'
  input_encoding: 'utf-8'
1% Converting input to HTML...
InputFormatPlugin: TXT Input running
on /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/test.txt
Reading text from file...
Using user specified input encoding of utf-8
Auto detected paragraph type as single
Auto detected formatting as heuristic
Running text through basic conversion...
Language not specified
Creator not specified
Building file list...
        Found files...
                 HTMLFile:0:a:'/mnt/c/Users/Alexander/ebook2audiobook/tmp/calibre_7.6.0_tmp_m2yh68mk/vbq9h872_plumber/index.html'
Normalizing filename cases
Rewriting HTML links
Parsing index.html ...
*********  Heuristic processing HTML  *********
flow is too short, not running heuristics
Forcing index.html into XHTML namespace
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1 items of level: p_1
Ignoring level p_1
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Running EPUB Output plugin
Splitting markup on page breaks and flow limits, if any...
        Looking for large trees in index.html...
        No large trees found
Generating default cover
This EPUB file has no Table of Contents. Creating a default TOC
EPUB output written to /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/__test.epub
Output saved to   /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-33b824f6-1a98-4f0d-bb39-cbaf746f7987/749f0afd72f75c2f83bbfab0b79f545b/__test.epub

/mnt/c/Users/Alexander/ebook2audiobook/python_env/lib/python3.12/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
******* NOTE: YOU CAN SAFELY IGNORE "Character xx not found in the vocabulary." *******
Loading TTS xtts model from /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987/xtts/model, it takes a while, please be patient...
coqui_tts_load_custom() error: Xtts.load_checkpoint() got an unexpected keyword argument 'enable_deepspeed'
convertsion 0.00%: 0/1 Part 1 containing 1 sentences...
Computing speaker latents...
convertsion 0.00%: 0/1
'NoneType' object has no attribute 'get_conditioning_latents'
Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 167, in convert_sentence_to_audio
    self.params['gpt_cond_latent'], self.params['speaker_embedding'] = self.params['tts'].get_conditioning_latents(audio_path=[self.params['voice_path']])
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/functions.py", line 675, in convert_chapters_to_audio
    if tts_manager.convert_sentence_to_audio():
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 286, in convert_sentence_to_audio
    raise ValueError(e)
ValueError: 'NoneType' object has no attribute 'get_conditioning_latents'
Caught DependencyError: 'NoneType' object has no attribute 'get_conditioning_latents'
convert_chapters_to_audio() failed!
```

**Comment by alexanderjacuna** [comment]
```
(base) alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook/models/__sessions$ cd model-33b824f6-1a98-4f0d-bb39-cbaf746f7987/
(base) alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987$ ls
xtts
(base) alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987$ cd xtts/
(base) alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987/xtts$ ls
model
(base) alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987/xtts$ cd model/
(base) alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-33b824f6-1a98-4f0d-bb39-cbaf746f7987/xtts/model$ ls
config.json  model.pth  ref.wav  vocab.json
```

**Comment by ROBERT-MCDOWELL** [comment]
please do it in headless mode, logs are more explicit

**Comment by alexanderjacuna** [comment]
Sorry about that, I'll do it in headless mode.

**Command used**
```bashe
./ebook2audiobook.sh \
--headless \
--ebook /mnt/c/Users/Alexander/ebook2audiobook/test.txt \
--custom_model /mnt/c/Users/Alexander/ebook2audiobook/model.zip \
--device gpu \
--tts_engine xtts \
--language eng 
```

**Output**
```
Running in native mode
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:29<00:00,  7.35s/files]
Extracted files to /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-26b4e2ea-5a08-4a7a-b4ed-842d62130245/xtts/model
Available Processor Unit: cuda
Running command: /usr/bin/ebook-convert /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-26b4e2ea-5a08-4a7a-b4ed-842d62130245/1a200d796fbe8c3cda9d9d56d4498565/test.txt /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-26b4e2ea-5a08-4a7a-b4ed-842d62130245/1a200d796fbe8c3cda9d9d56d4498565/__test.epub --input-encoding=utf-8 --output-profile=generic_eink --verbose
Conversion options changed from defaults:
  input_encoding: 'utf-8'
  verbose: 1
  output_profile: 'generic_eink'
1% Converting input to HTML...
InputFormatPlugin: TXT Input running
on /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-26b4e2ea-5a08-4a7a-b4ed-842d62130245/1a200d796fbe8c3cda9d9d56d4498565/test.txt
Reading text from file...
Using user specified input encoding of utf-8
Auto detected paragraph type as single
Auto detected formatting as heuristic
Running text through basic conversion...
Language not specified
Creator not specified
Building file list...
        Found files...
                 HTMLFile:0:a:'/mnt/c/Users/Alexander/ebook2audiobook/tmp/calibre_7.6.0_tmp_gamgi4cd/2nz8iu50_plumber/index.html'
Normalizing filename cases
Rewriting HTML links
Parsing index.html ...
*********  Heuristic processing HTML  *********
flow is too short, not running heuristics
Forcing index.html into XHTML namespace
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1 items of level: p_1
Ignoring level p_1
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Running EPUB Output plugin
Splitting markup on page breaks and flow limits, if any...
        Looking for large trees in index.html...
        No large trees found
Generating default cover
This EPUB file has no Table of Contents. Creating a default TOC
EPUB output written to /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-26b4e2ea-5a08-4a7a-b4ed-842d62130245/1a200d796fbe8c3cda9d9d56d4498565/__test.epub
Output saved to   /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-26b4e2ea-5a08-4a7a-b4ed-842d62130245/1a200d796fbe8c3cda9d9d56d4498565/__test.epub

/mnt/c/Users/Alexander/ebook2audiobook/python_env/lib/python3.12/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
******* NOTE: YOU CAN SAFELY IGNORE "Character xx not found in the vocabulary." *******
Loading TTS xtts model from model, it takes a while, please be patient...
coqui_tts_load_custom() error: Xtts.load_checkpoint() got an unexpected keyword argument 'enable_deepspeed'
convertsion 0.00%: 0/1 Part 1 containing 1 sentences...
Computing speaker latents...
convertsion 0.00%: 0/1
'NoneType' object has no attribute 'get_conditioning_latents'
Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 167, in convert_sentence_to_audio
    self.params['gpt_cond_latent'], self.params['speaker_embedding'] = self.params['tts'].get_conditioning_latents(audio_path=[self.params['voice_path']])
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/functions.py", line 675, in convert_chapters_to_audio
    if tts_manager.convert_sentence_to_audio():
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 286, in convert_sentence_to_audio
    raise ValueError(e)
ValueError: 'NoneType' object has no attribute 'get_conditioning_latents'
Caught DependencyError: 'NoneType' object has no attribute 'get_conditioning_latents'
```

**Comment by ROBERT-MCDOWELL** [comment]
ok merged. it should work now. git pull....

**Comment by ROBERT-MCDOWELL** [comment]
ah ok, sorry, it's eb2ab, it should delete only if it's in GUI mode, not headless. I fix it with the other fix.

**Comment by alexanderjacuna** [comment]
Rerunning again after recreating my model.zip file. Not sure I should run it in the same dir as the git project now but whatever. So good news is that DrewThomasson/ebook2audiobook#278 is gone.

**Command used**
```
./ebook2audiobook.sh \
--headless \
--ebook /mnt/c/Users/Alexander/ebook2audiobook/test.txt \
--custom_model /mnt/c/Users/Alexander/ebook2audiobook/model.zip \
--device gpu \
--tts_engine xtts \
--language eng 

```

**Output**
```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:28<00:00,  7.22s/files]
Extracted files to /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-7e910810-397e-47fd-9ef2-132e70209ea7/xtts/model
Available Processor Unit: cuda
Running command: /usr/bin/ebook-convert /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-7e910810-397e-47fd-9ef2-132e70209ea7/1a200d796fbe8c3cda9d9d56d4498565/test.txt /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-7e910810-397e-47fd-9ef2-132e70209ea7/1a200d796fbe8c3cda9d9d56d4498565/__test.epub --input-encoding=utf-8 --output-profile=generic_eink --verbose
Conversion options changed from defaults:
  output_profile: 'generic_eink'
  input_encoding: 'utf-8'
  verbose: 1
1% Converting input to HTML...
InputFormatPlugin: TXT Input running
on /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-7e910810-397e-47fd-9ef2-132e70209ea7/1a200d796fbe8c3cda9d9d56d4498565/test.txt
Reading text from file...
Using user specified input encoding of utf-8
Auto detected paragraph type as single
Auto detected formatting as heuristic
Running text through basic conversion...
Language not specified
Creator not specified
Building file list...
        Found files...
                 HTMLFile:0:a:'/mnt/c/Users/Alexander/ebook2audiobook/tmp/calibre_7.6.0_tmp_3vz3en72/753ndqo0_plumber/index.html'
Normalizing filename cases
Rewriting HTML links
Parsing index.html ...
*********  Heuristic processing HTML  *********
flow is too short, not running heuristics
Forcing index.html into XHTML namespace
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1 items of level: p_1
Ignoring level p_1
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Running EPUB Output plugin
Splitting markup on page breaks and flow limits, if any...
        Looking for large trees in index.html...
        No large trees found
Generating default cover
This EPUB file has no Table of Contents. Creating a default TOC
EPUB output written to /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-7e910810-397e-47fd-9ef2-132e70209ea7/1a200d796fbe8c3cda9d9d56d4498565/__test.epub
Output saved to   /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-7e910810-397e-47fd-9ef2-132e70209ea7/1a200d796fbe8c3cda9d9d56d4498565/__test.epub

/mnt/c/Users/Alexander/ebook2audiobook/python_env/lib/python3.12/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
******* NOTE: YOU CAN SAFELY IGNORE "Character xx not found in the vocabulary." *******
Loading TTS xtts model from model, it takes a while, please be patient...
coqui_tts_load_custom() error: 'NoneType' object has no attribute 'to'
convertsion 0.00%: 0/1 Part 1 containing 1 sentences...
Computing speaker latents...
convertsion 0.00%: 0/1
'NoneType' object has no attribute 'get_conditioning_latents'
Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 167, in convert_sentence_to_audio
    self.params['gpt_cond_latent'], self.params['speaker_embedding'] = self.params['tts'].get_conditioning_latents(audio_path=[self.params['voice_path']])
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/functions.py", line 675, in convert_chapters_to_audio
    if tts_manager.convert_sentence_to_audio():
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 286, in convert_sentence_to_audio
    raise ValueError(e)
ValueError: 'NoneType' object has no attribute 'get_conditioning_latents'
Caught DependencyError: 'NoneType' object has no attribute 'get_conditioning_latents'
```

**Comment by ROBERT-MCDOWELL** [comment]
I merged the deleted zip file bug. merged also the bug above, but it's to get more accuracy of where the issue occurs

**Comment by macramores** [comment]
latest txt for me with the update on docker

[logs.txt](https://github.com/user-attachments/files/18829838/logs.txt)

**Comment by ROBERT-MCDOWELL** [comment]
@macramores ok thanks my fix is not working. next PR will be solved tonight

**Comment by ROBERT-MCDOWELL** [comment]
ok merged! hope this time it's the right one!

**Comment by derbruedi** [comment]
for me it doesnt work i try it with WebUI and --headless
Running in native mode
Extracted files to J:\voice\ebook2audiobook\models\__sessions\model-80234a9e-6078-4586-9eda-1b7750aeb3ce\xtts\martin
Available Processor Unit: cuda
Running command: C:\Program Files\Calibre2\ebook-convert.EXE J:\voice\ebook2audiobook\tmp\ebook-80234a9e-6078-4586-9eda-1b7750aeb3ce\b2d02b67d18746ec0e7ca81ac2a57fdf\maddrax.txt J:\voice\ebook2audiobook\tmp\ebook-80234a9e-6078-4586-9eda-1b7750aeb3ce\b2d02b67d18746ec0e7ca81ac2a57fdf\__maddrax.epub --input-encoding=utf-8 --output-profile=generic_eink --verbose
Conversion options changed from defaults:
  input_encoding: 'utf-8'
  verbose: 1
  output_profile: 'generic_eink'
1% Eingabe wird zu HTML konvertiert …
InputFormatPlugin: TXT Input running
on J:\voice\ebook2audiobook\tmp\ebook-80234a9e-6078-4586-9eda-1b7750aeb3ce\b2d02b67d18746ec0e7ca81ac2a57fdf\maddrax.txt
Reading text from file...
Using user specified input encoding of utf-8
Auto detected paragraph type as single
Auto detected formatting as heuristic
Running text through basic conversion...
Language not specified
Creator not specified
Building file list...
	Found files...
		 HTMLFile:0:a:'J:\\voice\\ebook2audiobook\\tmp\\calibre_zi02errr\\tu6af7pa_plumber\\index.html'
Normalizing filename cases
Rewriting HTML links
Parsing index.html ...
*********  Heuristic processing HTML  *********
There are 24 blank lines. 0.4897959183673469 percent blank
minimum chapters required are: 1
found 0 pre-existing headings
numeric had 1 hits - 1 chapters with no title, 0 chapters with titles, 0.0 percent. 
Marked 0 headings, Searching for numeric chapter headings
marked 1 chapters. - 56. Tag
Total wordcount is: 442, Average words per section is: 442, Marked up 1 chapters
deleting blank lines
Hard line breaks check returned False
Median line length is 41, calculated with html format
Fixing hyphenated content
Formatting scene breaks
Forcing index.html into XHTML namespace
34% Umwandlungen am eBook werden ausgeführt …
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 24 items of level: p_1
Ignoring level p_1
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% EPUB Output-Erweiterung wird ausgeführt
Splitting markup on page breaks and flow limits, if any...
		Splitting on page-break at id=calibre_pb_0
	Looking for large trees in index.html...
	No large trees found
	Split into 2 parts
Generating default cover
This EPUB file has no Table of Contents. Creating a default TOC
EPUB output written to J:\voice\ebook2audiobook\tmp\ebook-80234a9e-6078-4586-9eda-1b7750aeb3ce\b2d02b67d18746ec0e7ca81ac2a57fdf\__maddrax.epub
Ausgabe gespeichert in   J:\voice\ebook2audiobook\tmp\ebook-80234a9e-6078-4586-9eda-1b7750aeb3ce\b2d02b67d18746ec0e7ca81ac2a57fdf\__maddrax.epub

******* NOTE: YOU CAN SAFELY IGNORE "Character xx not found in the vocabulary." *******
Loading TTS xtts model from martin, it takes a while, please be patient...
coqui_tts_load_custom() error: 'NoneType' object has no attribute 'to'
Part 1 containing 7 sentences...
Computing speaker latents...
'NoneType' object has no attribute 'get_conditioning_latents'
Caught DependencyError: 'NoneType' object has no attribute 'get_conditioning_latents'

**Comment by ROBERT-MCDOWELL** [comment]
@derbruedi provide the full command line or tell me if it's on GUI with a screenshot.
did you git pull just now?

**Comment by alexanderjacuna** [comment]
Haven't tested webui yet but this is headless output and command.

**Git pull**
```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook$ git pull
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 52 (delta 30), reused 31 (delta 25), pack-reused 12 (from 1)
Unpacking objects: 100% (52/52), 16.66 KiB | 54.00 KiB/s, done.
From https://github.com/DrewThomasson/ebook2audiobook
   6c9ff7b..1bebfef  main       -> origin/main
Updating 6c9ff7b..1bebfef
Fast-forward
 .github/workflows/docker_build_workflow.yml |  8 ++++----
 Dockerfile                                  |  2 +-
 Mac Ebook2Audiobook Launcher.command        |  4 ++++
 README.md                                   | 22 ++++++++--------------
 app.py                                      |  2 +-
 docker-compose.yml                          |  1 -
 ebook2audiobook.cmd                         | 71 ++++++++++++++++++++++++++++++++++++++++++++---------------------------
 lib/classes/voice_extractor.py              | 19 ++++++++++---------
 lib/conf.py                                 |  2 +-
 lib/functions.py                            | 55 ++++++++++++++++++++++++++++++++++++-------------------
 10 files changed, 109 insertions(+), 77 deletions(-)
 mode change 100644 => 100755 Mac Ebook2Audiobook Launcher.command

```

**Command used**
```
alexanderacuna@alex-desktop:/mnt/c/Users/Alexander/ebook2audiobook$ ./ebook2audiobook.sh \
> --headless \
> --ebook /mnt/c/Users/Alexander/ebook2audiobook/test.txt \
> --custom_model /mnt/c/Users/Alexander/ebook2audiobook/model.zip \
> --device gpu \
> --tts_engine xtts \
age eng> --language eng
```

**Output**
```
Running in native mode
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:30<00:00,  7.54s/files]
Extracted files to /mnt/c/Users/Alexander/ebook2audiobook/models/__sessions/model-1b98a856-a1ea-4a35-bcb4-82f5fdeb16ff/xtts/model
Available Processor Unit: cuda
Running command: /usr/bin/ebook-convert /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-1b98a856-a1ea-4a35-bcb4-82f5fdeb16ff/1a200d796fbe8c3cda9d9d56d4498565/test.txt /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-1b98a856-a1ea-4a35-bcb4-82f5fdeb16ff/1a200d796fbe8c3cda9d9d56d4498565/__test.epub --input-encoding=utf-8 --output-profile=generic_eink --verbose
Conversion options changed from defaults:
  input_encoding: 'utf-8'
  output_profile: 'generic_eink'
  verbose: 1
1% Converting input to HTML...
InputFormatPlugin: TXT Input running
on /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-1b98a856-a1ea-4a35-bcb4-82f5fdeb16ff/1a200d796fbe8c3cda9d9d56d4498565/test.txt
Reading text from file...
Using user specified input encoding of utf-8
Auto detected paragraph type as single
Auto detected formatting as heuristic
Running text through basic conversion...
Language not specified
Creator not specified
Building file list...
        Found files...
                 HTMLFile:0:a:'/mnt/c/Users/Alexander/ebook2audiobook/tmp/calibre_7.6.0_tmp_r2l6n04s/307bquv0_plumber/index.html'
Normalizing filename cases
Rewriting HTML links
Parsing index.html ...
*********  Heuristic processing HTML  *********
flow is too short, not running heuristics
Forcing index.html into XHTML namespace
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1 items of level: p_1
Ignoring level p_1
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Running EPUB Output plugin
Splitting markup on page breaks and flow limits, if any...
        Looking for large trees in index.html...
        No large trees found
Generating default cover
This EPUB file has no Table of Contents. Creating a default TOC
EPUB output written to /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-1b98a856-a1ea-4a35-bcb4-82f5fdeb16ff/1a200d796fbe8c3cda9d9d56d4498565/__test.epub
Output saved to   /mnt/c/Users/Alexander/ebook2audiobook/tmp/ebook-1b98a856-a1ea-4a35-bcb4-82f5fdeb16ff/1a200d796fbe8c3cda9d9d56d4498565/__test.epub

/mnt/c/Users/Alexander/ebook2audiobook/python_env/lib/python3.12/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
******* NOTE: YOU CAN SAFELY IGNORE "Character xx not found in the vocabulary." *******
Loading TTS xtts model from model, it takes a while, please be patient...
coqui_tts_load_custom() error: 'NoneType' object has no attribute 'to'
convertsion 0.00%: 0/1 Part 1 containing 1 sentences...
Computing speaker latents...
convertsion 0.00%: 0/1
'NoneType' object has no attribute 'get_conditioning_latents'
Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 167, in convert_sentence_to_audio
    self.params['gpt_cond_latent'], self.params['speaker_embedding'] = self.params['tts'].get_conditioning_latents(audio_path=[self.params['voice_path']])
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_conditioning_latents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/functions.py", line 680, in convert_chapters_to_audio
    if tts_manager.convert_sentence_to_audio():
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Alexander/ebook2audiobook/lib/classes/tts_manager.py", line 286, in convert_sentence_to_audio
    raise ValueError(e)
ValueError: 'NoneType' object has no attribute 'get_conditioning_latents'
Caught DependencyError: 'NoneType' object has no attribute 'get_conditioning_latents'
```

**Comment by ROBERT-MCDOWELL** [comment]
could you share your model.zip?

**Comment by ROBERT-MCDOWELL** [comment]
the last model.zip you used

**Comment by alexanderjacuna** [comment]
https://drive.google.com/drive/folders/1FTh5DfTNvc0agUx9_TgawhzY8Cv-afAl?usp=sharing

**Comment by ROBERT-MCDOWELL** [comment]
request access... nevermind I succeeded to reproduce it... I'm working on it.

**Comment by ROBERT-MCDOWELL** [comment]
the custom model uploads well and is on the custom list on GUI, it's a headless issue only now.

**Comment by derbruedi** [comment]
i am blind and have no plan how to upload screenshots but i hope that this are the right. 

![Image](https://github.com/user-attachments/assets/5f8dac5a-f1b7-4883-b59a-b5ac45c5e1f9)
![Image](https://github.com/user-attachments/assets/26106946-34bf-4cf6-9d20-ce3339ec7ed3)

**Comment by ROBERT-MCDOWELL** [comment]
ok fixed!.

**Comment by alexanderjacuna** [comment]
Let me know when I am good to git pull and confirm.

**Comment by derbruedi** [comment]
ok when i start ebook2audiobook.cmd i get this error 

![Image](https://github.com/user-attachments/assets/029e8c43-5107-42db-9b1f-b68788160865)

**Comment by ROBERT-MCDOWELL** [comment]
sorry you git pulled within 2 pushes... wait a sec thanks

**Comment by ROBERT-MCDOWELL** [comment]
ok you can git pull again.

**Comment by derbruedi** [comment]
ok works for me thanks

**Comment by ROBERT-MCDOWELL** [comment]
I still need to fix the  voice cloning upload but should be fixed tonight

**Comment by alexanderjacuna** [comment]
Holy smokes it worked.

**Comment by derbruedi** [comment]
it works but i have the problem that the sentenses not complete there is a speaker latens i can post the output later i hope the screenshots are ok and thanks for this cool program

**Comment by derbruedi** [comment]
ok here is my error

![Image](https://github.com/user-attachments/assets/292b4deb-368b-435d-952a-7a9ae8368b8e)

**Comment by ROBERT-MCDOWELL** [comment]
@derbruedi sorry I cannot see any error on this end of log. do you have  a new error?
run git pull again thanks.

**Comment by ROBERT-MCDOWELL** [comment]
everytime ebook2audiobook is stopped and start again in gradio GUI mode, so the web page must always been refreshed to reconnect to the gradio socket.
