### ISSUE TITLE
Words and sentences are skipped in latest version

### ISSUE THREAD

**Issue by clemcer** [DrewThomasson/ebook2audiobook#387]
**Script Mode**
- Docker

**Process Mode**
- Gradio GUI
  
**Operating System:**
 - Docker (Linux)

**Version**
- The current docker version

**Language**
- German

## The Issue:

I am on the latest version of this program (I will reference the latest version with 'v25' in this text), words, parts of sentences or even whole sentences are skipped during audio generation. This issue did not occur in v1.0.

### Logs
Here are the **logs** of both v25 and v1.0 generating audio for the same text.
I also used the same voice (custom model). 
In v25 there were a lot of words/sentences being skipped (see screenshots), in v1.5 nothing like that happened.

[e2a_v.25.log.txt](https://github.com/user-attachments/files/19040334/e2a_v.2.5.log.txt)
[e2a_v1.0.log.txt](https://github.com/user-attachments/files/19040333/e2a_v1.0.log.txt)

### Screenshots
Here are some **screenshots** from the logs of v2.5 where I marked the skipped parts in red:
<div align="center">
   <img src="https://github.com/user-attachments/assets/2a9eac7b-aca1-4633-909c-daf2c51278eb" alt="image" width="150" height="auto">

   <img src="https://github.com/user-attachments/assets/be505725-b4ed-461a-9e3b-a9bed68cb5da" alt="image" width="150" height="auto">

<img src="https://github.com/user-attachments/assets/ba69582d-8f81-427f-b749-a0b60a5fad18" alt="image" width="150" height="auto">

<img src="https://github.com/user-attachments/assets/be405979-c3f5-496a-8025-9284a8848f28" alt="image" width="150" height="auto">

<img src="https://github.com/user-attachments/assets/172c5842-7034-4911-bb55-f0f6966969a9" alt="image" width="150" height="auto">
</div>

### Additional Notes
While I don't know the inner workings of the program I did notice differences between v25 and v1.0 in the way the sentences are split and structured in the logs (see log file attachments above). 

I suspect the problem might be related to sentence splitting, as in v25 the text is not split correctly between sentences like in v1.0 (see the attached logs). However, it could also be caused by the three dots (...) that are placed after each sentence in v1.0 and no longer in v25.

Some voices in v25 perform better and skip fewer words or sentences, but the voice that performed the worst in v25 had no issues at all in v1.0.

Side Notes:

- I had to manually replace these (»«) marks with normal quotation marks (" ") in v1.0 to avoid hallucinations, as this issue is only fixed in v2.5.
 -  There were some instances where the full stop was pronounced, but it only happened two or three times and this is a minor issue compared to the skipping of sentences in v2.5.

If there is anything else I could do, just ask :)
Thanks for your great work!

**Comment by ROBERT-MCDOWELL** [comment]
v2.5 is NOT the last version, and old version are not supported anymore.

**Comment by clemcer** [comment]
Sorry I meant the newest version, v25. I will edit my post. 
And it is not fixed, I'm sorry to say. 
I am on the latest docker version and have done a lot of testing. Maybe the issue you are referring to is another language or something but in german the program is not really usable currently because as I stated in the issue and as you can see in the attached screenshots there is a lot of stuff being skipped.

**Comment by ROBERT-MCDOWELL** [comment]
it is believe me, I passed days on it with another german user 2 weeks ago.
clone the git repo again and reinstall a fresh eb2ab in native mode rather than docker and tell me if it's still occuring.

**Comment by clemcer** [comment]
The latest docker version is only a couple of days old so I really doubt that it is going to be different in native mode. And trust me with this docker version there definitevely is an issue because with v1.0 there is no problem.
I could try tomorrow (it is evening here) if you really think native is better that docker at the moment. 

What is the issue you are referring to? I cant seem to find it

**Comment by ROBERT-MCDOWELL** [comment]
I'm maintaining the code, I know what I'm talking about.... docker is always a littl behind the last git version.

**Comment by clemcer** [comment]
You are completely right! I just did some testing in native mode and it does seem to be fixed. Only in one of my three tests there was one occurence of some words being skipped. 

I don't understand why it does not work in docker though. I even built the docker image locally myself with the current files and the Dockerfile from the github repo and it still had the same bug. 
So it seems that the docker image somehow works differently than the native script.

I noticed another minor issue as well in native mode. It often happens that there are no pauses between sentences, which makes the text sound less natural and fluent. 

I could open another issue for that if you want but maybe first we figure out why the docker image still has the bug even though I built it locally with the current repo? Maybe it is fixed when you build the container and I made a mistake.

**Comment by ROBERT-MCDOWELL** [comment]
> Only in one of my three tests there was one occurence of some words being skipped.
send whih sentence with which punctuation causing that.

> I don't understand why it does not work in docker though
again, docker is for now behind the native last git, since Drew and I are working on ebook2audiobook when we have time. and time is money....

> So it seems that the docker image somehow works differently than the native script
no it's not, it's just a little up to date.

> I noticed another minor issue as well in native mode. It often happens that there are no pauses between sentences, which makes the text sound less natural and fluent.
If there is a dot or comma, it should be, if there is no punctuation and just a space or new line, it's not. we cannot consider a new line as a pause, since many ebooks has new lines without the mean to be an end of sentence.

> I could open another issue 
as long as we have no other complain about it, it's better you go to our discord channel category "docker, talks" to discuss with others.

**Comment by clemcer** [comment]
> again, docker is for now behind the native last git, since Drew and I are working on ebook2audiobook when we have time. and time is money....

Yes, but I built the docker image myself with the current files fom the repo and the Dockerfile from the repo so my local docker image should be up to date. That's what I don't understand. But then again, maybe Drew uses a different Dockerfile or something.  

---

> send which sentence with which punctuation causing that.

Here is the part from the terminal log. The part that was skipped is in bold.

Sentence: dass er lächelte . "Wir fragen uns nur , wer für die Bewachung verantwortlich war . " Hermine drängte **_weiter . "Wir fragen uns ,_**
Converting 27.27%: : 9/33 
Sentence: wem Dumbledore genug Vertrauen entgegenbringt , um ihn um Hilfe zu bitten , abgesehen natürlich von dir .
Converting 30.30%: : 10/33 

But as I said, this only happened in one of the three tests that I did.

---

> as long as we have no other complain about it, it's better you go to our discord channel category "docker, talks" to discuss with others.

Okay. I mean, this problem is pretty consistent throughout the whole text and in all my three tests in native mode so I would be surprised if I was the only one with this issue. But I can ask in the discord channel first if you prefer that

**Comment by clemcer** [comment]
> If there is a dot or comma, it should be, if there is no punctuation and just a space or new line, it's not. we cannot consider a new line as a pause, since many ebooks has new lines without the mean to be an end of sentence.

No, it happens everytime there is dot in between two sentences (except for when the program processes the two sentences separately I think).

So for example, in this sentence there are two dots and both times there is no pause:

Converting 30.30%: : 10/33 
Sentence: " Bei ihren letzten Worten schwoll Hagrids Brust an . Harry und Ron strahlten zu Hermine hinüber . "Nun gut , ich denk nicht ,
Converting 33.33%: : 11/33

**Comment by ROBERT-MCDOWELL** [comment]
ok so you confirm the skipping words are fixed on your last tests with the last git?
> So for example, in this sentence there are two dots and both times there is no pause:
which tts engine are you using? which fine tuned?

**Comment by ROBERT-MCDOWELL** [comment]
this is absolutely the FIRST thing you had to tell me that you didn't use our fine tuned models or the internal one.
could you realize that each fine tuned behaves differently and so it becomes impossible for us to fix a bug if you start to use ebook2audiobook with your own fine fined model?

**Comment by clemcer** [comment]
That is why I did not open a new issue immediately and asked you about it beforehand. If I had opened a new issue I would have provided everything as I did with this issue. 

I am sorry if you feel like you wasted time on this but I don't think you did. I tested it with another voice just now (the best one I have trained so far) and the bug is still there. 

I am pretty sure it is not because of the voice because EVERY TIME there is a dot between two sentences there is no pause. That does not seem to be a problem of just one voice.

Just tell me what you need. I can try with the normal built in german voice now or all of the other voices I have trained so far.

**Comment by ROBERT-MCDOWELL** [comment]
we don't provide any support for private xttsv2 fine tuned models.
other deutsch users didn't reported issues like no pause between a dot with the internal and official xttsv2 fine tuned.
you can have what you think your own best xttsv2 fine tuned model but this is not our concern and interest to fix it for you.

**Comment by clemcer** [comment]
## First things first:

> we don't provide any support for private xttsv2 fine tuned models.

Saying you don't support custom fine tuned models makes no sense because the built in german voice is pretty bad compared to fine tuned models. It speaks very slowly and produces a lot of hallucinations. All these hallucinations and the slow speaking make it hard to tell if the issue with the missing pauses is still there (I think it is though).

So in short, compared to the built in German voice the fine tuned models provide a much better baseline for how well this program is working.


> other deutsch users didn't reported issues like no pause between a dot with the internal and official xttsv2 fine tuned.

Maybe I am just the first user who reports this issue? The issue is very new afterall especially when you consider that many people are using docker which still is not on this latest version and still has the other bug for which I opened this issue.
Furthermore this issue occurs so frequently and with all the voices I've tried that I am sure I will not be the only one reporting it.


## Regarding the bug
I have now **converted the same text with FIVE different custom models** (all if which are better than the built in voice). In every one of these tests I had the same issue and **it happened consistently EVERY TIME** two sentences are separated by a dot (except for sentences that were processed separately). 

Here is a short audio of with three sentences separated by a dot with no pauses:
[three_dots_no_pauses.mp3.zip](https://github.com/user-attachments/files/19044451/three_dots_no_pauses.mp3.zip)

Here is the terminal log. 
[terminal.log](https://github.com/user-attachments/files/19044453/terminal.log)

And here is the text I used:
[harry_potter_pauses.txt](https://github.com/user-attachments/files/19044458/hagrid_with_gansef_oben.txt)

## Additional Notes

I really don't know why you seem so angry. I have invested a lot of time now testing the program and obviously just want to help. 
I was not asking you to solve this issue immediately, in fact I told you it is a minor issue and that I could open another issue some other time. You were the one asking me questions about it and now you complain?

All I wanted and still want to do is help you improve this program, but in the end this is your project and if this is how you want to treat users who just want to help then that is your thing. 
**If you do want to work on this bug and need something from me I would be happy to assist, if you don't then I won't bother with this project anymore because help is clearly not appreciated.**

**Comment by DrewThomasson** [comment]
@clemcer 
So I may be a bit confused as I'm suddenly jumping into this convo, 

But the only thing we can help with is making sure that custom xtts models imports are treated the same as the default xtts model

Have you tried isolating the issue to make sure that it's not an issue with how custom xtts models are used?

#### Does normally using the default xtts model, run into this sentence skipping issue?

#### Does importing the same default xtts model _as a custom model_ lead to this sentence skipping issue?

Cause if importing the same standard base model makes it somehow treated differently and leads to this sentence skipping issue, then that's something we can probs look into.

**Comment by ROBERT-MCDOWELL** [comment]
@clemcer  
- ebook2audiobook is not the author of xttsv2 and all other tts engine with builtin models, if you want to complain or improve the builtin tts engine model just go to their repo and talk to them. example, the maintained repo of xttsv2 is https://github.com/idiap/coqui-ai-TTS
- you still not understand my request, so I ask again: is the internal german xttsv2 german model makes pauses or not with the dot?
- you have german custom models working better than the internal? ok, share it to us once this dot resolved and we will integrate it by default for german language.
if  you think I'm "angry" (which is a very strong word in English), you misunderstood totally. but to NOT want believe or understand the maintainers which Drew and I are, so this is almost disrespectful.

**Comment by clemcer** [comment]
@DrewThomasson 

Thanks a lot fur jumping into this. **First of all the issue we are currently discussing is NOT the one I opened this issue for.** This new bug is minor compared to the other one. I had asked whether I should open a new issue but he said no and then proceeded asking questions under this issue which is why we are here now.

The issue I opened with (the skipping of sentences) is only present when using docker. **In native mode the issue is fixed, sentences are no longer being skipped.**
This was a bit confusing to me because even when I built the image locally myself with the current repo the bug was still there. But maybe I made a mistake while building the image and the bug will gone when you push a new update.

While testing the program in native mode I stumbled over this **new bug** which had not been there with the apparently not up to date docker version I was using before.

### The new bug:
There are no pauses between sentences. Every time there is a dot between two sentences there is no pause between them (except for when the sentences are being processed separately in different fragments. Here is an [example](https://github.com/DrewThomasson/ebook2audiobook/issues/387#issuecomment-2692723798)  from earlier.

### Now to your questions:

> But the only thing we can help with is making sure that custom xtts models imports are treated the same as the default xtts model

I do admit that I was slightly confused regarding the differences between finetuned models and your built in voice.

I think I know what you mean now. You are not the devs of the xxts finetune and thus can't fix their issues. **However in previous ebook2audiobook versions this bug was not there (when using fine tuned models) which makes it unlikely that it is a bug in the xtts finetune program instead of ebook2audiobook**. I probably was not clear enough about that.

## Furthermore I just tested it in english 
... with David Attenborough and the bug is still there
Here you can hear it:

https://github.com/user-attachments/assets/a80e2d11-ad17-452d-9590-2b4adf239475

Here is a zip containing the generated audio, the terminal log and the text I used with the David Attenborough voice. 
[attenborough_no_pauses.zip](https://github.com/user-attachments/files/19052385/attenborough_no_pauses.zip)

Note that as I said, it **only happens with sentences that are separated by a dot and only when the sentences are processed by the program in the same fragment.** 
For some reason in english in doesn't happen every time like in German but still frequently enough that you notice it.

And as I said this is a minor bug and nothing urgent but it is still disturbing the flow of the audio.

---

> Does normally using the default xtts model, run into this sentence skipping issue?

I did do some tests with the default German voice but as I said the program is not really usable with this voice because it speaks very slowly and has lots of hallucinations. With all these hallucinations and slow speaking I can hardly even tell if there are pauses between sentences. 
There were only some cases when there were no hallucinations  where I could check for this bug and: This bug seems to be better with the built in voice compared to finetuned models but there still were some instances with no pauses. I don't know what to make of that. And again it really is hard to tell because of all the problems with the voice.

As I said before, I could open a new issue since this is not the bug I opened the issue for. Just tell me if you need anything from me or whether you want to work on this bug at all.

**Comment by ROBERT-MCDOWELL** [comment]
are you on our discord channels? I would like to make some tests with you to fix this "dot" issue. I have an idea but not sure if it will work for all languages.

**Comment by clemcer** [comment]
> only that is not normal, xttsv2 will never deliver a model causing a lot of hallucinations. I suspect you have fine tuned parameters set to cause all these hallucinations

I mean, I could try again but I didn't change any settings. Are you sure the default german voice is a finetuned one? Because under fine tuned Models there is nothing so I just used the default German voice. I am not a developer and don't know the details of your program or and am not really sure about the differences between the built in voices. Here is a screenshot showing you where I selected the german voice. It does not seem to be a fine tuned one, does it?

![Image](https://github.com/user-attachments/assets/68f5e8da-7771-4528-af38-9a1978de55f4)

> are you on our discord channels? I would like to make some tests with you to fix this "dot" issue. I have an idea but not sure if it will work for all languages.

So you confirm that it is not just an issue on my side? And I don't have to install everything from scratch because it is my fault?
Yes, I will write you on discord. I dont have time all day but can definitely do some testing. Thanks for acknowledging the issue

**Comment by ROBERT-MCDOWELL** [comment]
please do what I'm requesting from you, it will go faster than turn around.
could you see the fine tuned parameters thumbnail close to "Main parameters"?
ok, click on it and reset all parameters with the little button on the right of each slide, to be sure that old cookies from previous wrong version of eb2ab will be wipe out.

**Comment by clemcer** [comment]
Yes, I did not forget about that. I will try to convert it again with all cookies deleted and parameters reset. I was just asking because you were talking about German xttsv2 and there is no built in fine tuned model in the drop down under "Fine Tuned Models" except for internal, which confused me.

But yes, I understood you and am trying again with the internal one.

I wrote you on discord btw. Just tell me what I should test to resolve the dot issue

**Comment by clemcer** [comment]
Okay, I can confirm now that I did not change the settings. Here you can see the default settings for yourself, I made sure to press on the reset button of every one of them:

![Image](https://github.com/user-attachments/assets/870a05de-997d-4615-8213-e3a1d7217844)

In my first run yesterday I counted 13 hallucinations, this time I counted 11 and one very weird one that sounded like the sound a bee makes:

https://github.com/user-attachments/assets/43f1c267-b143-45bf-88b1-599152a26de9

Anyway, this is not the main issue and can be easily fixed by replacing the voice or is there anything else you want me to do?

**Comment by ROBERT-MCDOWELL** [comment]
Do you understand what I'm asking to you? I don't care you change or not the settings, I ask you to reset them with the reset button on right of each slide. is it too much for you to do it?

**Comment by clemcer** [comment]
please just read my comment. 

> Here you can see the default settings for yourself, I made sure to press on the reset button of every one of them:

is this not exactly what you asked me to do? 
If you want me to pull some new changes you made with new default settings **then say that**. But I did do git pull just now and **pressed on every reset button** after I deleted all my cookies (even in incognito mode) and they are exactly the same as in the image. 

So no, it is not too much for me.
Seriously I really have invested a lot of time into this discussion and have been nothing but constuctive at every step but I really am slowly losing my patience with you.

**Comment by ROBERT-MCDOWELL** [comment]
repetition_penalty=2.4 and try again.
this is my last comment for this issue, I need to spend my time to wrap up other issues and push an update.
you will get more patience to get your issue solved, learning how to respect a ilttle more developers spending their time for free on github to satisfy users, not to get invectives nor disrespect from guys like you.

**Comment by DrewThomasson** [comment]
Latest docker updated to current main: 0518b955a66ff5cf4c2f5673f563c0392b713792

Ref to GitHub Action: -> https://github.com/DrewThomasson/ebook2audiobook/actions/runs/13637397974

**Comment by DrewThomasson** [comment]
@clemcer 
#### Related about your custom models: If you provide a huggingface or something with the model I would gladly integrate them into our existing models list.

Or you can also make a PR to add them to my https://huggingface.co/drewThomasson/fineTunedTTSModels

### If so please make sure to include the files in this format for each model.

- {VoiceNameNoSpaces}_1600.wav -> (Example `AiExplained_1600.wav` Best if cut down to around 10 seconds or less)
- {VoiceNameNoSpaces}_2400.wav -> (Example `AiExplained_2400.wav` Best if cut down to around 10 seconds or less)
- config.json
- model.pth
- speakers_xtts.pth (optional)
- vocab.json
- ref.wav (optional unmodified full length ref file)
- generated_example.wav (Optional but helpful for seeing the quality)

Thank you :)

**Comment by ROBERT-MCDOWELL** [comment]
@boolemancer
this is made on purpose and has nothing to do with your issue. btw

**Comment by ROBERT-MCDOWELL** [comment]
> I noticed that in `lib/lang.py` ([link here](https://github.com/DrewThomasson/ebook2audiobook/blob/0518b955a66ff5cf4c2f5673f563c0392b713792/lib/lang.py#L67))
> 
> punctuation_list = [
>     # Common punctuation in Western languages
>     ".", ", ", ":", ";", "!", "?", "¡", "¿", "«", "»",
> It looks like a space was inadvertently added to the comma's punctuation. This results in the `punctuation_pattern_spaces` and `punctuation_pattern_split` regexes considering a space character to be punctuation when I imagine they probably shouldn't, which drastically changes what the `phoneme_list` looks like when it gets passed down to `get_sentences`.
> 
> I wonder if that could have an impact on the issue that [@clemcer](https://github.com/clemcer) was seeing?

correction: this was a typo, or more precisely a forgotten correction where a space was on all punctuation because of a previous function with a different logic. thanks to report it.

**Comment by DrewThomasson** [comment]
I guess I'll close this issue then

**Comment by ROBERT-MCDOWELL** [comment]
no yet, I want to know why so many hallucinations with german language builtin model.

**Comment by clemcer** [comment]
I have been using a workaround for the issue with the missing pauses. I am sure there is a much better way of solving this and maybe you alreay have but I thought maybe this is of interest to you.
As I said, when a sentence ends with a dot but the new sentence is processed in a new fragment there _is_ a pause. But if the sentence ends with a dot and the new sentence starts in the same processed fragment there is _not_ a pause.

So I just inserted 4 lines of code in the [get_sentences](https://github.com/DrewThomasson/ebook2audiobook/blob/02c21478f2bc7ef7f5ca7f64deeb1fde8677f916/lib/functions.py#L584) function to split a sentence after _every_ dot and not just when the max_tokens is reached.
It is a very rudimentary solution and brings it own set of new problems (when there are three dots for example) but for me it has been working great.

```
def get_sentences(phoneme_list, max_tokens):
    sentences = []
    current_sentence = ""
    current_phoneme_count = 0
    for phoneme in phoneme_list:
        part_phoneme_count = len(phoneme.split())

        #### ADDED BY CLEMCER 
        if current_sentence.endswith('.'):
            sentences.append(current_sentence.strip())
            current_sentence = phoneme
            current_phoneme_count = part_phoneme_count             

        # Always append to current sentence unless punctuation is hit
        elif current_phoneme_count + part_phoneme_count > max_tokens:
            # Ensure we finalize the sentence at punctuation, not a space
            if any(current_sentence.endswith(punc) for punc in punctuation_list):
                sentences.append(current_sentence.strip())
                current_sentence = phoneme
                current_phoneme_count = part_phoneme_count
            else:
                # Look back and split at last punctuation instead of splitting randomly
                last_punc_index = max(
                    (current_sentence.rfind(punc) for punc in punctuation_list if punc in current_sentence),
                    default=-1
                )
                if last_punc_index > -1:
                    sentences.append(current_sentence[:last_punc_index+1].strip())  # Keep punctuation
                    current_sentence = current_sentence[last_punc_index+1:].strip() + " " + phoneme
                    current_phoneme_count = len(current_sentence.split())
                else:
                    sentences.append(current_sentence.strip())
                    current_sentence = phoneme
                    current_phoneme_count = part_phoneme_count
        else:
            current_sentence += (" " if current_sentence else "") + phoneme
            current_phoneme_count += part_phoneme_count
    if current_sentence:
        sentences.append(current_sentence.strip())
    return sentences
```

**Comment by ROBERT-MCDOWELL** [comment]
the entire function among other on this subject has been rebased for the next update.
